fix
Signed-off-by: wangli <wangli858794774@gmail.com>

diff --git a/.github/workflows/_e2e_nightly_multi_node.yaml b/.github/workflows/_e2e_nightly_multi_node.yaml
--- a/.github/workflows/_e2e_nightly_multi_node.yaml
+++ b/.github/workflows/_e2e_nightly_multi_node.yaml
@@ -181,6 +181,18 @@ jobs:
           run: |
             kubectl logs -f "$LEADER_POD" -n "$NAMESPACE"
 
+        - name: Determine is success
+          run: |
+            set -euo pipefail
+            echo "Checking for error files in ${RESULT_DIR} ..."
+            if compgen -G "${RESULT_DIR}/error*" > /dev/null; then
+              echo "Found error logs:"
+              ls -1 "${RESULT_DIR}/error"*
+              exit 1
+            else
+              echo "No error files found."
+            fi
+
         - name: Post process
           if: always()
           run: |
