rebase
Signed-off-by: wangli <wangli858794774@gmail.com>

diff --git a/.github/workflows/_e2e_nightly_multi_node.yaml b/.github/workflows/_e2e_nightly_multi_node.yaml
--- a/.github/workflows/_e2e_nightly_multi_node.yaml
+++ b/.github/workflows/_e2e_nightly_multi_node.yaml
@@ -260,8 +260,36 @@ jobs:
               fi
             done
 
+        - name: Determine if test passed
+          id: determine_passed
+          run: |
+            RESULT_FILE_PATH="$RESULT_FILE"/ret_"${{ inputs.soc_version }}"
+            config_file_name=$(basename "${{ inputs.config_file_path }}" .yaml)
+            RESULT_FILE_PATH="${RESULT_FILE_PATH}_${config_file_name}"
+
+            echo "RESULT_FILE_PATH=$RESULT_FILE_PATH" >> $GITHUB_ENV
+
+            if [ -d "$RESULT_FILE_PATH/plogs" ]; then
+              echo "fail=true" >> $GITHUB_ENV
+              echo "Test failed: plogs directory found."
+              exit 1
+            else
+              echo "fail=false" >> $GITHUB_ENV
+              echo "Test passed: No plogs directory found."
+            fi
+
+        - name: Upload Report
+          if: failure()
+          uses: actions/upload-artifact@v5
+          with:
+            name: logs
+            path: ${{ env.RESULT_FILE_PATH }}
+            if-no-files-found: warn
+            retention-days: 3
+            overwrite: true
+
         - name: Post process
           if: always()
           run: |
-            kubectl get pods -n $NAMESPACE
-            kubectl delete -f ./lws.yaml
+            kubectl get pods -n $NAMESPACE --ignore-not-found=true
+            kubectl delete -f ./lws.yaml --ignore-not-found=true || true
